"""Install/uninstall the router's hooks into the user's ``~/.cursor/hooks.json``.

Only entries whose ``command`` was generated by this installer are ever
added or removed; every other hook already configured by the user (or by
another tool) is left untouched. A timestamped backup is written before any
change so a bad merge can always be reverted by hand.
"""

from __future__ import annotations

import json
import shutil
import sys
from datetime import datetime
from pathlib import Path

HOOKS_FILE_RELATIVE = Path(".cursor") / "hooks.json"

# Every event this project subscribes to; kept in one place so install and
# uninstall stay in sync with cursor_model_router.collector.events.
SUBSCRIBED_EVENTS: tuple[str, ...] = (
    "sessionStart",
    "beforeSubmitPrompt",
    "preToolUse",
    "postToolUse",
    "postToolUseFailure",
    "afterFileEdit",
    "stop",
    "sessionEnd",
)

_LEGACY_MARKER = "# cursor-model-router"


def resolve_router_command() -> str:
    """Return a quoted, absolute invocation of the installed ``router`` CLI.

    Prefers the console script sitting next to the current interpreter (the
    venv/install this package was installed into) over relying on ``PATH``,
    since the shell Cursor invokes hooks from may not share the caller's
    activated environment.
    """
    scripts_dir = Path(sys.executable).parent
    candidate_names = ["router.exe", "router"] if sys.platform == "win32" else ["router"]
    for name in candidate_names:
        candidate = scripts_dir / name
        if candidate.exists():
            return f'"{candidate}" hook'
    which_result = shutil.which("router")
    if which_result:
        return f'"{which_result}" hook'
    return "router hook"


def _is_router_command(command: str, expected_command: str) -> bool:
    """Recognize current commands and the broken marker-based legacy form."""
    return command == expected_command or _LEGACY_MARKER in command


def _hooks_file_path(home_override: Path | None = None) -> Path:
    home = home_override or Path.home()
    return home / HOOKS_FILE_RELATIVE


def _load_hooks_document(path: Path) -> dict:
    if not path.exists():
        return {"version": 1, "hooks": {}}
    with path.open("r", encoding="utf-8") as handle:
        document = json.load(handle)
    document.setdefault("version", 1)
    document.setdefault("hooks", {})
    return document


def _backup(path: Path) -> Path | None:
    if not path.exists():
        return None
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    backup_path = path.with_suffix(f".json.{timestamp}.bak")
    shutil.copy2(path, backup_path)
    return backup_path


def install_user_hooks(home_override: Path | None = None) -> Path:
    path = _hooks_file_path(home_override)
    document = _load_hooks_document(path)
    command = resolve_router_command()

    for event_name in SUBSCRIBED_EVENTS:
        entries = document["hooks"].setdefault(event_name, [])
        router_entry = next(
            (
                entry
                for entry in entries
                if _is_router_command(entry.get("command", ""), command)
            ),
            None,
        )
        if router_entry is None:
            entries.append({"command": command, "failClosed": False})
        else:
            # Upgrade the legacy command in place. Its trailing ``#`` comment
            # broke Cursor's generated PowerShell wrapper on Windows.
            router_entry["command"] = command
            router_entry["failClosed"] = False

    _backup(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(document, handle, indent=2)
        handle.write("\n")
    return path


def uninstall_user_hooks(home_override: Path | None = None) -> Path:
    path = _hooks_file_path(home_override)
    document = _load_hooks_document(path)
    command = resolve_router_command()

    for event_name in SUBSCRIBED_EVENTS:
        entries = document["hooks"].get(event_name, [])
        remaining = [
            entry
            for entry in entries
            if not _is_router_command(entry.get("command", ""), command)
        ]
        if remaining:
            document["hooks"][event_name] = remaining
        else:
            document["hooks"].pop(event_name, None)

    _backup(path)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(document, handle, indent=2)
        handle.write("\n")
    return path
